# Project-wide Gradle settings.
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Enable AndroidX and Jetifier to support backward compatibility
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official

# Optimize Gradle daemon JVM performance
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC -Dfile.encoding=UTF-8

# Allow non-ASCII characters in project path
android.overridePathCheck=true
